import type { FC, ReactNode } from "react";
import { useState } from "react";
import Head from "next/head";
import { AppShell } from "@mantine/core";

import { NavbarComponent } from "./NavbarComponent";
import { HeaderComponent } from "./HeaderComponent";

type Props = {
  title: string;
  children: ReactNode;
};

export const Layout: FC<Props> = ({ children, title = "T3 Stack" }) => {
  const [navbarOpened, setNavbarOpened] = useState(false);

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <AppShell
        padding="md"
        navbarOffsetBreakpoint="sm"
        navbar={<NavbarComponent navbarOpened={navbarOpened} />}
        header={
          <HeaderComponent
            navbarOpened={navbarOpened}
            setNavbarOpened={setNavbarOpened}
          />
        }
      >
        {children}
      </AppShell>
    </>
  );
};
