import type { FC, ReactNode } from "react";
import Head from "next/head";
import { Grid } from "@mantine/core";

type Props = {
  title: string;
  children: ReactNode;
};

export const Layout: FC<Props> = ({ children, title = "T3 Stack" }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="bg-gray-100">
        <Grid justify="center">
          <Grid.Col xs={12} sm={8} md={6} xl={6}>
            {children}
          </Grid.Col>
        </Grid>
      </main>
    </>
  );
};
